version: "3"
services:
  city-api:
    image: org.k3yake/city-api:latest
    container_name: city-api
    ports:
      - "8080:8080"
    links:
      - db
  db:
    image: mysql:latest
    container_name: city-api-db
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
networks:
  default: