apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: city-api
  name: city-api
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: city-api
    spec:
      containers:
      - image: localhost:5000/org.k3yake/city-api:20180429153711
        name: city-api
        ports:
        - containerPort: 8080
        resources: {}
        env:
         - name: "DB_HOST"
           value: "city-api-db"
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 30
      restartPolicy: Always
status: {}
