apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: city-api
  name: city-api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: city-api
    spec:
      containers:
      - image: localhost:5000/org.k3yake/city-api:latest
        name: city-api
        ports:
        - containerPort: 8080
        resources: {}
        env:
         - name: "DB_HOST"
           value: "10.104.80.3"
      restartPolicy: Always
status: {}
